- id: '1677425932357'
  alias: Morning
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: 0
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.sfeer_verlichting_uit
    metadata: {}
  - service: scene.turn_on
    target:
      entity_id: scene.lore_dag
    metadata: {}
  mode: single
- id: '1677426092006'
  alias: Morning - dark
  description: ''
  trigger:
  - platform: time
    at: 05:00:00
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.sfeer_verlichting
    metadata: {}
  - service: scene.turn_on
    target:
      entity_id: scene.lore_nacht
    metadata: {}
  mode: single
- id: '1677426135907'
  alias: Sunset
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: 0
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.sfeer_verlichting
    metadata: {}
  mode: single
- id: '1677426175883'
  alias: Sleep
  description: ''
  trigger:
  - platform: time
    at: '23:30:00'
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.sfeer_verlichting_uit
    metadata: {}
  mode: single
- id: '1677426217383'
  alias: Sleep kids
  description: ''
  trigger:
  - platform: time
    at: '20:00:00'
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.lore_nacht
    metadata: {}
  mode: single
- id: '1681129255425'
  alias: Verwarming keuken/schuifraam
  description: ''
  use_blueprint:
    path: SmartLiving.Rocks/window-open-climate-off.yaml
    input:
      window_entity: binary_sensor.schuifraam
      minimum_open_time: 60
      minimum_close_time: 60
      climate_target: climate.living_keuken
- id: '1681129811337'
  alias: Nachtlicht - Keuken
  description: ''
  use_blueprint:
    path: Blackshome/sensor-light.yaml
    input:
      motion_trigger:
      - binary_sensor.keuken
      include_sun: sun_enabled
      include_time: time_enabled
      before_time: 05:00:00
      light_switch:
        entity_id: light.innr_sp_220_switch
- id: '1682431869099'
  alias: Low battery level alert
  description: ''
  use_blueprint:
    path: sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      actions:
      - service: notify.notify
        data:
          title: Low battery
          message: Low battery detected for {{sensors}}
- id: '1682799509784'
  alias: Water tuin start
  description: ''
  trigger:
  - platform: state
    entity_id:
    - timer.watermoestuin
    to: active
  condition: []
  action:
  - type: turn_on
    device_id: 61eb1d7b85861127eec592fe53726d3c
    entity_id: switch.valve_tuin_switch
    domain: switch
  mode: single
- id: '1682799647623'
  alias: Water tuin stop
  description: ''
  trigger:
  - platform: state
    entity_id:
    - timer.watermoestuin
    to: idle
  - platform: state
    entity_id:
    - timer.watermoestuin
    to: paused
  condition: []
  action:
  - type: turn_off
    device_id: 61eb1d7b85861127eec592fe53726d3c
    entity_id: switch.valve_tuin_switch
    domain: switch
  mode: single
- id: '1684064279466'
  alias: Knop - Bewatering
  description: ''
  trigger:
  - device_id: 5276f7a099d12bb3d2c609c285834eb1
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  condition: []
  action:
  - service: script.bewateringtimerstart
    data: {}
  mode: single
- id: '1689932629976'
  alias: Vacation Mode On
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.vacation_mode
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 0
  condition: []
  action:
  - service: notify.notify
    data:
      message: Vakantie modus geactiveerd. Verwarming gedactiveerd en lampen in vakantie
        modus.
      title: Vakantie modus
  - service: scene.turn_on
    target:
      entity_id: scene.away_heating
    metadata: {}
  mode: single
- id: '1689932743570'
  alias: Vacation Mode Off
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.vacation_mode
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 0
  condition: []
  action:
  - service: notify.notify
    data:
      message: Vakantie modus gedactiveerd
      title: Vakantie modus
  - service: scene.turn_on
    target:
      entity_id: scene.home_heating
    metadata: {}
  mode: single
- id: '1690118731278'
  alias: Vacation - Dissarm notification
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.brand_altijd_actief
    to: DISARMED
  condition:
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'on'
  action:
  - service: notify.notify
    data:
      title: Alarm uitgeschakeld
      message: Het alarm is uitgeschakeld tijdens vakantie modus
  mode: single
- id: '1690817702235'
  alias: Voortuin Detectie - Timer start
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.voortuindetectiemodus
    to: 'on'
  condition: []
  action:
  - service: timer.start
    data: {}
    target:
      entity_id: timer.voortuindetectietimer
  mode: single
- id: '1690817779007'
  alias: Voortuin Detectie - Reset
  description: ''
  trigger:
  - platform: state
    entity_id:
    - timer.voortuindetectietimer
    to: idle
  condition: []
  action:
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.voortuindetectiemodus
  mode: single
- id: '1690817934043'
  alias: Voortuin detectie - Notificatie
  description: ''
  use_blueprint:
    path: SgtBatten/Stable.yaml
    input:
      camera: camera.cam_voordeur
      notify_device: e1124791e33b420b5fbe74d3f53e459e
      state_entity: input_boolean.voortuindetectiemodus
      state_filter_states:
      - 'on'
      state_filter: true
      critical: 'false'
      attachment: snapshot
      ios_live_view: true
      labels:
      - person
- id: '1691312023323'
  alias: Voortuin - TTS Notification
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.cam_voordeur_person_occupancy
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.voortuindetectiemodus
    state: 'on'
  action:
  - service: script.aankondiging
    data:
      message: Er is iemand aan de deur gedetecteerd
  mode: single
- id: '1691323175287'
  alias: Agenda Aankondiging
  description: ''
  trigger:
  - platform: calendar
    event: start
    offset: 0:0:0
    entity_id: calendar.family_bell
  condition:
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  action:
  - service: script.aankondiging
    data:
      message: '{{ trigger.calendar_event.summary }}'
  mode: single
- id: '1691509122619'
  alias: Verbruik - Dag piek
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.p1_meter_5c2faf058214_active_power
    for:
      hours: 0
      minutes: 20
      seconds: 0
    above: 3000
  condition:
  - condition: state
    entity_id: sensor.p1_meter_5c2faf058214_active_tariff
    state: '1'
  action:
  - service: notify.notify
    data:
      message: Piek verbruik gedecteerd op dag tarief, huidige verbruik {{ trigger.to_state
        }}W (>{{ trigger.above }})
      title: Piek verbruik
  mode: single
- id: '1692084563677'
  alias: Night - Vacation
  description: ''
  trigger:
  - platform: time
    at: 01:05:00
  condition:
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'on'
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.lore_dag
    metadata: {}
  mode: single
