mqtt:
  host: 192.168.1.144
  user: mqtt-lcl
  password: --REDACTED--
  
database:
  path: /config/frigate.db

detectors:
  coral:
    type: edgetpu
    device: usb

go2rtc:
  streams:
    stream_voordeur:
      - http://192.168.100.6/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=homeassistant&password=--REDACTED--
      - ffmpeg:stream_voordeur#audio=opus
    stream_voordeur_sub:
      - http://192.168.100.6/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=homeassistant&password=--REDACTED--
    stream_stal:
      - http://192.168.1.159/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=homeassistant&password=--REDACTED--
      - ffmpeg:stream_stal#audio=opus
    stream_stal_sub:
      - http://192.168.1.159/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=homeassistant&password=--REDACTED--

cameras:
  cam-voordeur:
    ffmpeg:
      hwaccel_args: preset-rpi-64-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/stream_voordeur?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/stream_voordeur_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    zones:
      zone_parking:
        coordinates: 0.481,0.226,0.682,0,0.872,0.098,0.812,0.302
        objects: person
        inertia: 3
        loitering_time: 0
      zone_oprit:
        coordinates: 0,319,523,180,452,134,0,278
      zone_klinkers:
        coordinates: 71,550,359,672,721,672,874,238,500,193,607,234,573,292
    objects:
      filters:
        car:
          mask: 685,0,606,49,773,91,827,39
        person:
          mask: 80,555,58,459,21,425,0,452,0,672,361,672,370,625,260,571,220,649
    review:
      alerts:
        required_zones:
          - zone_oprit
          - zone_klinkers
      detections:
        required_zones:
          - zone_oprit
          - zone_klinkers
  cam-tuin:
    ffmpeg:
      hwaccel_args: preset-rpi-64-h264
      inputs:
        - path: rtsp://homeassistant:--REDACTED--@192.168.100.11:554//h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://homeassistant:--REDACTED--@192.168.100.11:554/
          roles:
            - record
    zones:
      zone_pad:
        coordinates: 0.32,0.688,0.451,0.485,0.396,0.49,0.138,0.656,0,0.747,0,1,1,1,1,0.85,0.386,0.813
        inertia: 3
        loitering_time: 0
      zone_tuin:
        coordinates: 
          0.384,0.796,0.653,0.843,1,0.849,1,0.466,1,0.39,0.578,0.457,0.452,0.497,0.329,0.687

        inertia: 3
        loitering_time: 0
  cam-stal:
    ffmpeg:
      hwaccel_args: preset-rpi-64-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/stream_stal?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/stream_stal_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect

detect:
  width: 896
  height: 672
  fps: 5

objects:
  track:
    - person
    - car
    - horse

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 10
    mode: active_objects

record:
  enabled: true
  events:
    retain:
      default: 10
version: 0.14
