mqtt:
  host: 192.168.1.144
  user: mqtt-lcl
  password: --REDACTED--
  
database:
  path: /config/frigate.db

detectors:
  coral:
    type: edgetpu
    device: usb

go2rtc:
  streams:
    stream_voordeur: 
      - http://192.168.1.154/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=homeassistant&password=--REDACTED--
      - "ffmpeg:stream_voordeur#audio=opus"
    stream_voordeur_sub: 
      - http://192.168.1.154/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=homeassistant&password=--REDACTED--
    stream_stal: 
      - http://192.168.1.159/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=homeassistant&password=--REDACTED--
      - "ffmpeg:stream_stal#audio=opus"
    stream_stal_sub: 
      - http://192.168.1.159/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=homeassistant&password=--REDACTED--
    
cameras:
  cam-voordeur:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/stream_voordeur?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/stream_voordeur_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    zones:  
      zone_parking:
        coordinates: 431,152,611,0,781,66,728,203
        objects:
        - person
      zone_oprit:
        coordinates: 0,319,523,180,452,134,0,278
      zone_klinkers:
        coordinates: 71,550,359,672,721,672,874,238,500,193,607,234,573,292
    objects:
        filters:
          car:
            mask: 
              685,0,606,49,773,91,827,39
          person:
            mask:
              80,555,58,459,21,425,0,452,0,672,361,672,370,625,260,571,220,649

  cam-tuin:
    ffmpeg:
      inputs: 
        - path: rtsp://homeassistant:--REDACTED--@192.168.1.145:554//h264Preview_01_sub 
          roles: 
            - detect 
            - rtmp 
        - path: rtsp://homeassistant:--REDACTED--@192.168.1.145:554/          
          roles: 
            - record
    zones:
      zone_pad:
        coordinates: 208,462,404,326,355,329,124,441,0,502,0,672,407,672
      zone_tuin:
        coordinates: 305,623,464,672,896,672,896,313,714,318,518,307,405,334,173,492

  cam-stal:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/stream_stal?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/stream_stal_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
  
detect:
  width: 896
  height: 672
  fps: 5
  
objects:
  track:
    - person
    - car
    - horse
    
snapshots: 
  enabled: True 
  timestamp: True 
  bounding_box: True 
  retain: 
    default: 10
    mode: active_objects

record:
  enabled: True
  events:
    required_zones:
        - zone_oprit
        - zone_klinkers
        - zone_pad
        - zone_tuin
    retain:
      default: 10
      mode: active_objects