mqtt:
  host: 192.168.1.144
  user: mqtt-lcl
  password: {PASSWORD}
  
database:
  path: /config/frigate.db

detectors:
  coral:
    type: edgetpu
    device: usb

go2rtc:
  streams:
    stream_voordeur: 
      - http://192.168.1.154/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=homeassistant&password=PASSWORD
      - "ffmpeg:stream_voordeur#audio=opus"
    stream_voordeur_sub: 
      - http://192.168.1.154/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=homeassistant&password=PASSWORD
    
cameras:
  cam-voordeur:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/stream_voordeur?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/stream_voordeur_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    zones:  
      zone_parking:
        coordinates: 431,152,578,57,750,94,728,203
        objects:
        - person
      zone_oprit:
        coordinates: 0,319,523,180,452,134,0,278
      zone_klinkers:
        coordinates: 71,550,359,672,721,672,874,238,500,193,607,234,573,292

    objects:
        filters:
            person:
              mask:
                80,555,58,459,21,425,0,452,0,672,361,672,370,625,260,571,220,649

  cam-tuin:
    ffmpeg:
      inputs: 
        - path: rtsp://homeassistant:PASSWORD@192.168.1.145:554//h264Preview_01_sub 
          roles: 
            - detect 
            - rtmp 
        - path: rtsp://homeassistant:PASSWORD@192.168.1.145:554/          
          roles: 
            - record
detect:
  width: 896
  height: 672
  fps: 5
  
objects:
  track:
    - person
    - car
    - horse
    
snapshots: 
  enabled: True 
  timestamp: True 
  bounding_box: True 
  crop: True 
  retain: 
    default: 10
    mode: active_objects

record:
  enabled: True
  retain:
    days: 14
    mode: active_objects
  events:
    retain:
      default: 10
      mode: active_objects