- id: '1677425720556'
  name: Sfeer verlichting
  entities:
    light.innr_sp_220_switch:
      supported_color_modes:
      - onoff
      friendly_name: Keuken lamp
      supported_features: 0
      color_mode: onoff
      state: 'on'
    switch.lamp_living_switch_4:
      friendly_name: Lamp Living Switch
      state: 'on'
  icon: mdi:lamps
  metadata:
    light.innr_sp_220_switch:
      entity_only: true
    switch.lamp_living_switch_4:
      entity_only: true
- id: '1677425786216'
  name: Sfeer verlichting uit
  entities:
    light.innr_sp_220_switch:
      supported_color_modes:
      - onoff
      friendly_name: Keuken lamp
      supported_features: 0
      state: 'off'
    switch.lamp_living_switch_4:
      friendly_name: Lamp Living Switch
      state: 'off'
  icon: mdi:lamps-outline
  metadata:
    light.innr_sp_220_switch:
      entity_only: true
- id: '1677426005316'
  name: Lore dag
  entities:
    light.innr_sp_220_switch_2:
      supported_color_modes:
      - onoff
      friendly_name: Lore nachtlamp
      supported_features: 0
      state: 'off'
  icon: mdi:lightbulb-off
  metadata:
    light.innr_sp_220_switch_2:
      entity_only: true
- id: '1677426028294'
  name: Lore nacht
  entities:
    light.innr_sp_220_switch_2:
      supported_color_modes:
      - onoff
      friendly_name: Lore nachtlamp
      supported_features: 0
      color_mode: onoff
      state: 'on'
  icon: mdi:lightbulb
  metadata:
    light.innr_sp_220_switch_2:
      entity_only: true
- id: '1689932314996'
  name: Away Heating
  entities:
    climate.thuis:
      hvac_modes:
      - 'off'
      - heat
      min_temp: 7
      max_temp: 35
      preset_modes:
      - eco
      - Reset
      - away
      - home
      - Custom
      current_temperature: 21.6
      preset_mode: away
      status:
        system_id: '2452718'
        active_system_faults: []
        system_mode_status:
          mode: Away
          is_permanent: true
      icon: mdi:thermostat
      friendly_name: Thuis
      supported_features: 16
      state: heat
  icon: mdi:hvac-off
  metadata:
    climate.thuis:
      entity_only: true
- id: '1689932348065'
  name: Home Heating
  entities:
    climate.thuis:
      hvac_modes:
      - 'off'
      - heat
      min_temp: 7
      max_temp: 35
      preset_modes:
      - eco
      - Reset
      - away
      - home
      - Custom
      current_temperature: 21.6
      preset_mode:
      status:
        system_id: '2452718'
        active_system_faults: []
        system_mode_status:
          mode: Auto
          is_permanent: true
      icon: mdi:thermostat
      friendly_name: Thuis
      supported_features: 16
      state: heat
  icon: mdi:hvac
  metadata:
    climate.thuis:
      entity_only: true
