bewateringtimerstart:
  alias: BewateringTimerStart
  sequence:
  - service: timer.start
    data:
      entity_id: timer.watermoestuin
      duration: '{{ states(''input_select.waterdoorlooptijd'') }}'
  mode: single
  icon: mdi:timer-play
aankondiging:
  alias: Aankondiging
  fields:
    message:
      description: The message content
      example: Test 123
  sequence:
  - service: media_player.play_media
    data:
      media_content_id: https://www.orangefreesounds.com/wp-content/uploads/2019/12/Announcement-sound-effect.mp3
      media_content_type: Music
    target:
      entity_id: media_player.living_room_speaker
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: tts.speak
    data:
      cache: true
      media_player_entity_id: media_player.living_room_speaker
      message: '{{ message }}'
      language: nl_BE
    target:
      entity_id: tts.piper
  - wait_for_trigger:
    - platform: state
      entity_id:
      - media_player.living_room_speaker
      from: playing
      to: idle
    timeout:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - service: media_player.play_media
    data:
      media_content_id: https://www.orangefreesounds.com/wp-content/uploads/2019/12/Announcement-sound-effect.mp3
      media_content_type: Music
    target:
      entity_id: media_player.living_room_speaker
  mode: single
  icon: mdi:account-voice
aankondiging_input:
  alias: Aankondiging Input
  sequence:
  - service: media_player.play_media
    data:
      media_content_id: https://www.orangefreesounds.com/wp-content/uploads/2019/12/Announcement-sound-effect.mp3
      media_content_type: Music
    target:
      entity_id: media_player.living_room_speaker
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: tts.speak
    data:
      cache: true
      media_player_entity_id: media_player.living_room_speaker
      message: '{{ states(''input_text.aankondigingbericht'') }}'
      language: nl_BE
    target:
      entity_id: tts.piper
  - wait_for_trigger:
    - platform: state
      entity_id:
      - media_player.living_room_speaker
      from: playing
      to: idle
    timeout:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - service: media_player.play_media
    data:
      media_content_id: https://www.orangefreesounds.com/wp-content/uploads/2019/12/Announcement-sound-effect.mp3
      media_content_type: Music
    target:
      entity_id: media_player.living_room_speaker
  mode: single
  icon: mdi:account-voice
christmas_sequence:
  alias: Christmas Sequence
  sequence:
  - service: media_player.turn_on
    target:
      entity_id: media_player.living_room_speaker
    data: {}
  - service: light.turn_off
    target:
      entity_id:
      - light.living_1
      - light.living_2
      - light.innr_sp_220_switch
      - light.lamp_living_switch
      - light.haard
    data: {}
  - parallel:
    - service: media_player.play_media
      target:
        entity_id: media_player.living_room_speaker_2
      data:
        media_content_id: '6915'
        media_content_type: playlist
      metadata:
        title: 'Spotify: Christmas Hits'
        thumbnail:
        media_class: playlist
        children_media_class:
        navigateIds:
        - {}
        - media_content_type: Playlists
          media_content_id: Playlists
    - choose:
      - conditions: []
        sequence:
        - service: light.turn_on
          data:
            effect: '10'
          target:
            entity_id:
            - light.living_1
            - light.living_2
        - delay:
            hours: 0
            minutes: 0
            seconds: 7
            milliseconds: 0
        - service: light.turn_on
          target:
            entity_id: light.sfeerverlichting
          data: {}
        - delay:
            hours: 0
            minutes: 0
            seconds: 50
            milliseconds: 0
        - service: light.turn_on
          target:
            entity_id:
            - light.living_1
            - light.living_2
          data:
            effect: '9'
        - service: light.turn_on
          data: {}
          target:
            entity_id: light.haard
  mode: restart
  icon: mdi:string-lights
playlist_person:
  alias: Playlist person
  sequence:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ person == "lore" }}'
      sequence:
      - service: media_player.play_media
        target:
          entity_id: media_player.moode
        data:
          media_content_id: '6979'
          media_content_type: playlist
        metadata:
          title: "Spotify: Peppa Pig Official Playlist \U0001F43D✨\U0001F3B5"
          thumbnail:
          media_class: playlist
          children_media_class:
          navigateIds:
          - {}
          - media_content_type: Playlists
            media_content_id: Playlists
    - conditions:
      - condition: template
        value_template: '{{ person == "jasper" }}'
      sequence:
      - service: media_player.play_media
        target:
          entity_id: media_player.moode
        data:
          media_content_id: '6997'
          media_content_type: playlist
        metadata:
          title: 'Spotify: Jasper'
          thumbnail:
          media_class: playlist
          children_media_class:
          navigateIds:
          - {}
          - media_content_type: Playlists
            media_content_id: Playlists
  mode: single
  icon: mdi:account-music
  fields:
    person:
      selector:
        select:
          options:
          - jasper
          - lore
      name: Person
      description: Name of the person
      required: true
